[package]
name = "stampede"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossbeam-channel.workspace = true
env_logger.workspace = true
ffmpeg-next.workspace = true
figment.workspace = true
log.workspace = true
media.workspace = true
serde.workspace = true
toml.workspace = true
